    export const KEYS = {
        FOLLOWS: 'follows',
        CONDUCTORS: 'conductors',
        CONTRIBUTORS: 'contributors',
        CHEERS: 'cheers',
        SUBS: 'subs',
        RE_SUBS: 'reSubs',
        GIFT_SUBS: 'giftSubs',
        GIFT_BOMBS: 'giftBombs',
        RAIDED: 'raided',
        REWARD_REDEMPTIONS: 'rewardRedemptions',
        GOAL_CONTRIBUTIONS: 'goalContributions',
        PYRAMIDS: 'pyramids',
        EDITORS: 'editors',
        MODERATORS: 'moderators',
        SUBSCRIBERS: 'subscribers',
        VIPS: 'vips',
        NOTABLE_USERS: 'NotableUsers',
        LOCAL_USERS: 'Local Users',
        USERS: 'users',
        CONDUCTORS: 'conductors',
        CONTRIBUTORS: 'contributors',
        ALL_BITS: 'allBits',
        MONTH_BITS: 'monthBits',
        WEEK_BITS: 'weekBits',
        CHANNEL_REWARDS: 'channelRewards',
    };